version: '3.1'
services:
  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3307:3306
    volumes:
      - data:/data
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: bookmanager



volumes:
  data: {}
